### PR TITLE
Fix search to be able to delete characters.

### LINKED ISSUE #9: Unable to clear while entering search command
After entering `/`, press `<Backspace>` to clear the search term, but it does not work.

### LINKED ISSUE #11: Unable to delete characters in command/search mode
You should be able to delete as follows:
- `:23` => `:2`
- `/str` => `/s`

### PR DESCRIPTION
**Pull request by eth-p**
Fixes #9
Fixes #11.

### CODE REVIEW

File: src/writer.rs [hunk 1]
```diff
@@ -400,6 +400,20 @@ impl<'b> UiContext<'b> {
                                 self.need_redraw = true;
                                 return Ok(false);
                             }
+                            KeyCode::Backspace => {
+                                let s_len = s.chars().count();
+                                if s_len == 0 {
```
Comment (Riey) [inline src/writer.rs]: You don't need to use count() check pop() return value whether Some or None

Comment (eth-p) [reply src/writer.rs]: > You don't need to use count() check pop() return value whether Some or None

Haha, good point. Fixed.

**Review by Riey — APPROVED** [review]
